name: yumemi_codecheck
description: 株式会社ゆめみのコードチェックにチャレンジ

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.15
  cloud_functions: ^3.2.17
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.1.10
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^2.0.3
  go_router: ^4.0.0
  http: ^0.13.4
  import_sorter: ^4.6.0
  intl: ^0.17.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  pedantic_mono: any
  freezed: ^2.0.3+1
  build_runner: ^2.1.11


flutter:

  uses-material-design: true
